apiVersion: v2
name: auralarchive
description: AuralArchive app subchart
type: application
version: 0.1.1
appVersion: 0.1.2
dependencies:
  - name: common
    repository: oci://oci.trueforge.org/truecharts
    version: 28.29.61
