apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "servarr.fullname" . }}-prowlarr-init
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    {{- with .Values.init.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "20"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20"
    #{{- end }}
spec:
  backoffLimit: {{ .Values.init.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.init.job.activeDeadlineSeconds }}
  template:
    metadata:
      name: "{{ include "servarr.fullname" . }}-prowlarr-finalizer"
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.init.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.init.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-prowlarr
          image: {{ .Values.init.waitFor.image.repository }}:{{ .Values.init.waitFor.image.tag }}
          imagePullPolicy: {{ .Values.init.waitFor.image.pullPolicy }}
          resources:
            {{- toYaml .Values.init.waitFor.resources | nindent 12 }}
          command:
            [
              "sh",
              "-c",
              "until wget --spider -S -T 10 \"http://{{ .Release.Name }}-prowlarr.{{ .Release.Namespace }}.svc.cluster.local:9696\" 2>&1 | grep -qw '200\\|301\\|302' > /dev/null ; do echo Waiting for servarr-prowlarr ; sleep 5 ; done ; sleep 10 ;",
            ]
      containers:
        - name: initialize-prowlarr
          image: {{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          resources:
            {{- toYaml .Values.init.resources | nindent 12 }}
          env:
            - name: STATE_FILE_PATH
              value: "/state/prowlarr_init_state.json"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PROWLARR_HOST
              value: "{{ .Release.Name }}-prowlarr.{{ .Release.Namespace }}.svc.cluster.local:9696"
            - name: API_KEY
              value: "{{ $.Values.global.apikey }}"
            - name: TORRENT_SERVICE
              value: "{{ .Release.Name }}-qbittorrent"
            - name: TORRENT_ADMIN
              value: "{{ $.Values.torrent.username }}"
            - name: TORRENT_PASSWORD
              value: "{{ $.Values.torrent.password }}"
            - name: PROWLARR_SERVICE
              value: "{{ .Release.Name }}-prowlarr:9696"
            - name: RADARR_SERVICE
              value: "{{ .Release.Name }}-radarr:7878"
            - name: FLARESOLVERR_SERVICE
              value: "{{ .Release.Name }}-flaresolverr:8191"
            - name: SONARR_SERVICE
              value: "{{ .Release.Name }}-sonarr:8989"
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - "pip install -r /scripts/requirements.txt && python3 -u /scripts/init-prowlarr.py 2>&1;"
          volumeMounts:
            - mountPath: "/scripts"
              name: python-script-and-indexers
            - mountPath: "/state"
              name: init-state
      volumes:
        - name: init-state
          persistentVolumeClaim:
            claimName: {{.Values.volumes.initConfig.name}}
        - name: python-script-and-indexers
          configMap:
            name: {{ include "servarr.fullname" . }}-init-scripts
