apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "servarr.fullname" . }}-bazarr-init
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
  annotations:
    {{- include "servarr.annotations" . | nindent 4 }}
    {{- with .Values.init.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    #{{- if not .Values.argoCD }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "20"
    #{{- if not .Values.debug }}
    helm.sh/hook-delete-policy: hook-failed
    #{{- end }}
    #{{- end }}

    #{{- if .Values.argoCD }}
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20"
    #{{- end }}
spec:
  backoffLimit: {{ .Values.init.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.init.job.activeDeadlineSeconds }}
  template:
    metadata:
      name: "{{ include "servarr.fullname" . }}-bazarr-finalizer"
      labels:
        {{- include "servarr.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.init.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.init.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-bazarr
          image: {{ .Values.init.waitFor.image.repository }}:{{ .Values.init.waitFor.image.tag }}
          imagePullPolicy: {{ .Values.init.waitFor.image.pullPolicy }}
          resources:
            {{- toYaml .Values.init.waitFor.resources | nindent 12 }}
          command:
            [
              "sh",
              "-c",
              "until wget --spider -S -T 10 \"http://{{ .Release.Name }}-bazarr.{{ .Release.Namespace }}.svc.cluster.local:6767\" 2>&1 | grep -qw '200\\|301\\|302' > /dev/null ; do echo Waiting for servarr-bazarr ; sleep 5 ; done ; sleep 10 ;",
            ]
      containers:
        - name: initialize-bazarr
          image: {{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          resources:
            {{- toYaml .Values.init.resources | nindent 12 }}
          env:
            - name: STATE_FILE_PATH
              value: "/state/bazarr_init_state.json"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BAZARR_HOST
              value: "{{ .Release.Name }}-bazarr.{{ .Release.Namespace }}.svc.cluster.local:6767"
            - name: API_KEY
              value: "{{ $.Values.global.apikey }}"
            - name: SONARR_HOST
              value: "{{ .Release.Name }}-sonarr.{{ .Release.Namespace }}.svc.cluster.local:8989"
            - name: SONARR_API_KEY
              value: "{{ $.Values.global.apikey }}"
            - name: RADARR_HOST
              value: "{{ .Release.Name }}-radarr.{{ .Release.Namespace }}.svc.cluster.local:7878"
            - name: RADARR_API_KEY
              value: "{{ $.Values.global.apikey }}"
            - name: PREFERRED_SUBTITLES_LANGUAGES
              value: "{{ $.Values.dash.preferredSubtitlesLanguages }}"
            - name: PREFERRED_SUBTITLES_PROVIDERS
              value: "{{ $.Values.dash.preferredSubtitlesProviders }}"
            - name: PREFERRED_SUBTITLES_PROVIDERS_SETTINGS
              value: "{{ $.Values.dash.preferredSubtitlesProvidersSettings }}"
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - "pip install -r /scripts/requirements.txt && python3 -u /scripts/init-bazarr.py 2>&1;"
          volumeMounts:
            - mountPath: "/scripts"
              name: python-script
            - mountPath: "/state"
              name: init-state
      volumes:
        - name: init-state
          persistentVolumeClaim:
            claimName: {{.Values.volumes.initConfig.name}}
        - name: python-script
          configMap:
            name: {{ include "servarr.fullname" . }}-init-scripts
